version: '3.8'

volumes:
  db-data:

networks:
  container-link:

services:
  mysql:
    # image: 333233774574.dkr.ecr.ap-northeast-1.amazonaws.com/bar-exam-database
    build:
      context: ./docker/mysql
      args:
        MYSQL_DATABASE: $MYSQL_DATABASE
        MYSQL_USER: $MYSQL_USER
        MYSQL_PASSWORD: $MYSQL_PASSWORD
        MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
        TZ: Asia/Tokyo
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - container-link
    platform: linux/amd64

  express:
    # image: 333233774574.dkr.ecr.ap-northeast-1.amazonaws.com/bar-exam-backend
    build:
      context: .
      dockerfile: ./docker/back/Dockerfile
      args:
        EMAIL_HOST: $EMAIL_HOST
        EMAIL_PORT: $EMAIL_PORT
        EMAIL_ADDRESS: $EMAIL_ADDRESS
        EMAIL_PASSWORD: $EMAIL_PASSWORD
        FRONTEND_URL: $FRONTEND_URL
        DB_HOST: $DB_HOST
        DB_PORT: $DB_PORT
        DB_USERNAME: $DB_USERNAME
        DB_PASSWORD: $DB_PASSWORD
        DB_DATABASE: $DB_DATABASE
    environment:
      - TZ=Asia/Tokyo
    tty: true
    ports:
      - 8080:8080
    volumes:
      - ./api:/node
    working_dir: /node
    command: [sh, -c, npm install && npm run dev]
    # command: [sh, -c, npm install && npm run start]
    networks:
      - container-link
    platform: linux/amd64
  
  nuxt:
    # image: 333233774574.dkr.ecr.ap-northeast-1.amazonaws.com/bar-exam-frontend
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
      args:
        BASE_URL: $BASE_URL
    command: ["yarn", "dev"]
    # command: ["yarn", "start"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    tty: true
    networks:
      - container-link
    platform: linux/amd64